//NPC relevant macro
`define     NPC_PC_SIZE    32
`define     NPC_XLEN        64
`define     NPC_INST_SIZE   32
// Decode relevant macro 
`define NPC_DECINFO_GRP_WIDTH   3
`define NPC_DECINFO_GRP_ALU     `NPC_DECINFO_GRP_WIDTH'd0
`define NPC_DECINFO_GRP_AGU     `NPC_DECINFO_GRP_WIDTH'd1
`define NPC_DECINFO_GRP_CSR     `NPC_DECINFO_GRP_WIDTH'd2
`define NPC_DECINFO_GRP_MULDIV  `NPC_DECINFO_GRP_WIDTH'd3
`define NPC_DECINFO_GRP_BJP     `NPC_DECINFO_GRP_WIDTH'd4

//NOT INCLUDE FLOAT POINT AT PRESENT 
    `define NPC_DECINFO_GRP_LSB     0
    `define NPC_DECINFO_GRP_MSB     (`NPC_DECINFO_GRP_LSB + `NPC_DECINFO_GRP_WIDTH -1)
`define NPC_DECINFO_GRP             `NPC_DECINFO_GRP_MSB:`NPC_DECINFO_GRP_LSB
`define NPC_DECINFO_SUBDECINFO_LSB  (`NPC_DECINFO_GRP_MSB + 1)

//ALU group 
    `define NPC_DECINFO_ALU_ADD_LSB `NPC_DECINFO_SUBDECINFO_LSB
    `define NPC_DECINFO_ALU_ADD_MSB (`NPC_DECINFO_ALU_ADD_LSB+1 -1)
`define NPC_DECINFO_ALU_ADD     `NPC_DECINFO_ALU_ADD_MSB:`NPC_DECINFO_ALU_ADD_LSB
    `define NPC_DECINFO_ALU_RV64W_LSB   (`NPC_DECINFO_ALU_ADD_MSB+1)
    `define NPC_DECINFO_ALU_RV64W_MSB   (`NPC_DECINFO_ALU_RV64W_LSB+1-1)
`define NPC_DECINFO_ALU_RV64W   `NPC_DECINFO_ALU_RV64W_MSB:`NPC_DECINFO_ALU_RV64W_LSB
    `define NPC_DECINFO_ALU_SUB_LSB (`NPC_DECINFO_ALU_RV64W_MSB+1)
    `define NPC_DECINFO_ALU_SUB_MSB (`NPC_DECINFO_ALU_SUB_LSB+1 -1)
`define NPC_DECINFO_ALU_SUB     `NPC_DECINFO_ALU_SUB_MSB:`NPC_DECINFO_ALU_SUB_LSB
    `define NPC_DECINFO_ALU_XOR_LSB (`NPC_DECINFO_ALU_SUB_MSB+1)
    `define NPC_DECINFO_ALU_XOR_MSB (`NPC_DECINFO_ALU_XOR_LSB+1 -1)
`define NPC_DECINFO_ALU_XOR     `NPC_DECINFO_ALU_XOR_MSB:`NPC_DECINFO_ALU_XOR_LSB
    `define NPC_DECINFO_ALU_SLL_LSB (`NPC_DECINFO_ALU_XOR_MSB+1)
    `define NPC_DECINFO_ALU_SLL_MSB (`NPC_DECINFO_ALU_SLL_LSB+1 -1)
`define NPC_DECINFO_ALU_SLL     `NPC_DECINFO_ALU_SLL_MSB:`NPC_DECINFO_ALU_SLL_LSB
    `define NPC_DECINFO_ALU_SRL_LSB (`NPC_DECINFO_ALU_SLL_MSB+1)
    `define NPC_DECINFO_ALU_SRL_MSB (`NPC_DECINFO_ALU_SRL_LSB+1 -1)
`define NPC_DECINFO_ALU_SRL     `NPC_DECINFO_ALU_SRL_MSB:`NPC_DECINFO_ALU_SRL_LSB
    `define NPC_DECINFO_ALU_SRA_LSB (`NPC_DECINFO_ALU_SRL_MSB+1)
    `define NPC_DECINFO_ALU_SRA_MSB (`NPC_DECINFO_ALU_SRA_LSB+1 -1)
`define NPC_DECINFO_ALU_SRA     `NPC_DECINFO_ALU_SRA_MSB:`NPC_DECINFO_ALU_SRA_LSB
    `define NPC_DECINFO_ALU_OR_LSB  (`NPC_DECINFO_ALU_SRA_MSB+1)
    `define NPC_DECINFO_ALU_OR_MSB  (`NPC_DECINFO_ALU_OR_LSB+1 -1)
`define NPC_DECINFO_ALU_OR      `NPC_DECINFO_ALU_OR_MSB:`NPC_DECINFO_ALU_OR_LSB
    `define NPC_DECINFO_ALU_AND_LSB (`NPC_DECINFO_ALU_OR_MSB+1)
    `define NPC_DECINFO_ALU_AND_MSB (`NPC_DECINFO_ALU_AND_LSB+1 -1)
`define NPC_DECINFO_ALU_AND     `NPC_DECINFO_ALU_AND_MSB:`NPC_DECINFO_ALU_AND_LSB
    `define NPC_DECINFO_ALU_SLT_LSB (`NPC_DECINFO_ALU_AND_MSB+1)
    `define NPC_DECINFO_ALU_SLT_MSB (`NPC_DECINFO_ALU_SLT_LSB+1 -1)
`define NPC_DECINFO_ALU_SLT     `NPC_DECINFO_ALU_SLT_MSB:`NPC_DECINFO_ALU_SLT_LSB
    `define NPC_DECINFO_ALU_SLTU_LSB (`NPC_DECINFO_ALU_SLT_MSB+1)
    `define NPC_DECINFO_ALU_SLTU_MSB (`NPC_DECINFO_ALU_SLTU_LSB+1 -1)
`define NPC_DECINFO_ALU_SLTU    `NPC_DECINFO_ALU_SLTU_MSB:`NPC_DECINFO_ALU_SLTU_LSB
    `define NPC_DECINFO_ALU_EBRK_LSB (`NPC_DECINFO_ALU_SLTU_MSB+1)
    `define NPC_DECINFO_ALU_EBRK_MSB (`NPC_DECINFO_ALU_EBRK_LSB+1 -1)
`define NPC_DECINFO_ALU_EBRK    `NPC_DECINFO_ALU_EBRK_MSB:`NPC_DECINFO_ALU_EBRK_LSB
    `define NPC_DECINFO_ALU_OP2IMM_LSB  (`NPC_DECINFO_ALU_EBRK_MSB+1)
    `define NPC_DECINFO_ALU_OP2IMM_MSB  (`NPC_DECINFO_ALU_OP2IMM_LSB+1 -1)
`define NPC_DECINFO_ALU_OP2IMM  `NPC_DECINFO_ALU_OP2IMM_MSB : `NPC_DECINFO_ALU_OP2IMM_LSB
    `define NPC_DECINFO_ALU_OP1PC_LSB   (`NPC_DECINFO_ALU_OP2IMM_MSB+1)
    `define NPC_DECINFO_ALU_OP1PC_MSB   (`NPC_DECINFO_ALU_OP1PC_LSB+1 -1)
`define NPC_DECINFO_ALU_OP1PC   `NPC_DECINFO_ALU_OP1PC_MSB:`NPC_DECINFO_ALU_OP1PC_LSB

`define NPC_DECINFO_ALU_WIDTH   (`NPC_DECINFO_ALU_OP1PC_MSB+1)

//AGU group
    `define NPC_DECINFO_AGU_LOAD_LSB    `NPC_DECINFO_SUBDECINFO_LSB
    `define NPC_DECINFO_AGU_LOAD_MSB    (`NPC_DECINFO_AGU_LOAD_LSB+1 -1)
`define NPC_DECINFO_AGU_LOAD    `NPC_DECINFO_AGU_LOAD_MSB:`NPC_DECINFO_AGU_LOAD_LSB
    `define NPC_DECINFO_AGU_STORE_LSB   (`NPC_DECINFO_AGU_LOAD_MSB+1)
    `define NPC_DECINFO_AGU_STORE_MSB   (`NPC_DECINFO_AGU_STORE_LSB+1 -1)
`define NPC_DECINFO_AGU_STORE   `NPC_DECINFO_AGU_STORE_MSB:`NPC_DECINFO_AGU_STORE_LSB
    `define NPC_DECINFO_AGU_USIGN_LSB   (`NPC_DECINFO_AGU_STORE_MSB+1)
    `define NPC_DECINFO_AGU_USIGN_MSB   (`NPC_DECINFO_AGU_USIGN_LSB+1 -1)
`define NPC_DECINFO_AGU_USIGN   `NPC_DECINFO_AGU_USIGN_MSB:`NPC_DECINFO_AGU_USIGN_LSB
    `define NPC_DECINFO_AGU_SIZE_LSB    (`NPC_DECINFO_AGU_USIGN_MSB+1)
    `define NPC_DECINFO_AGU_SIZE_MSB    (`NPC_DECINFO_AGU_SIZE_LSB+4-1)
`define NPC_DECINFO_AGU_SIZE    `NPC_DECINFO_AGU_SIZE_MSB:`NPC_DECINFO_AGU_SIZE_LSB
//NOT SUPPORT ATOMIC EXTENSION AT PRESENT
    `define NPC_DECINFO_AGU_WIDTH   (`NPC_DECINFO_AGU_SIZE_MSB+1)
    
//BXX group
    `define NPC_DECINFO_BJP_JAL_LSB    `NPC_DECINFO_SUBDECINFO_LSB
    `define NPC_DECINFO_BJP_JAL_MSB    (`NPC_DECINFO_BJP_JAL_LSB+1 -1)
`define NPC_DECINFO_BJP_JAL    `NPC_DECINFO_BJP_JAL_MSB:`NPC_DECINFO_BJP_JAL_LSB
    `define NPC_DECINFO_BJP_JALR_LSB    (`NPC_DECINFO_BJP_JAL_MSB+1)
    `define NPC_DECINFO_BJP_JALR_MSB    (`NPC_DECINFO_BJP_JALR_LSB+1 -1)
`define NPC_DECINFO_BJP_JALR    `NPC_DECINFO_BJP_JALR_MSB:`NPC_DECINFO_BJP_JALR_LSB
    `define NPC_DECINFO_BJP_BEQ_LSB     (`NPC_DECINFO_BJP_JALR_MSB+1)
    `define NPC_DECINFO_BJP_BEQ_MSB     (`NPC_DECINFO_BJP_BEQ_LSB+1 -1)
`define NPC_DECINFO_BJP_BEQ     `NPC_DECINFO_BJP_BEQ_MSB:`NPC_DECINFO_BJP_BEQ_LSB
    `define NPC_DECINFO_BJP_BNE_LSB     (`NPC_DECINFO_BJP_BEQ_MSB+1)
    `define NPC_DECINFO_BJP_BNE_MSB     (`NPC_DECINFO_BJP_BNE_LSB+1 -1)
`define NPC_DECINFO_BJP_BNE     `NPC_DECINFO_BJP_BNE_MSB:`NPC_DECINFO_BJP_BNE_LSB
    `define NPC_DECINFO_BJP_BLT_LSB     (`NPC_DECINFO_BJP_BNE_MSB+1)
    `define NPC_DECINFO_BJP_BLT_MSB     (`NPC_DECINFO_BJP_BLT_LSB+1 -1)
`define NPC_DECINFO_BJP_BLT     `NPC_DECINFO_BJP_BLT_MSB:`NPC_DECINFO_BJP_BLT_LSB
    `define NPC_DECINFO_BJP_BGT_LSB     (`NPC_DECINFO_BJP_BLT_MSB+1)
    `define NPC_DECINFO_BJP_BGT_MSB     (`NPC_DECINFO_BJP_BGT_LSB+1 -1)
`define NPC_DECINFO_BJP_BGT     `NPC_DECINFO_BJP_BGT_MSB:`NPC_DECINFO_BJP_BGT_LSB
    `define NPC_DECINFO_BJP_BLTU_LSB    (`NPC_DECINFO_BJP_BGT_MSB+1)
    `define NPC_DECINFO_BJP_BLTU_MSB    (`NPC_DECINFO_BJP_BLTU_LSB+1 -1)
`define NPC_DECINFO_BJP_BLTU    `NPC_DECINFO_BJP_BLTU_MSB:`NPC_DECINFO_BJP_BLTU_LSB
    `define NPC_DECINFO_BJP_BGEU_LSB    (`NPC_DECINFO_BJP_BLTU_MSB+1)
    `define NPC_DECINFO_BJP_BGEU_MSB    (`NPC_DECINFO_BJP_BGEU_LSB+1 -1)
`define NPC_DECINFO_BJP_BGEU    `NPC_DECINFO_BJP_BGEU_MSB:`NPC_DECINFO_BJP_BGEU_LSB
    `define NPC_DECINFO_BJP_BXX_LSB     (`NPC_DECINFO_BJP_BGEU_MSB+1)
    `define NPC_DECINFO_BJP_BXX_MSB     (`NPC_DECINFO_BJP_BXX_LSB+1 -1)
`define NPC_DECINFO_BJP_BXX     `NPC_DECINFO_BJP_BXX_MSB:`NPC_DECINFO_BJP_BXX_LSB

`define NPC_DECINFO_BJP_WIDTH   (`NPC_DECINFO_BJP_BXX_MSB+1)

//CSR group
//WE NOT SUPPROT CSR instruction AT PRESENT

//MULDIV group
    `define NPC_DECINFO_MULDIV_MUL_LSB  `NPC_DECINFO_SUBDECINFO_LSB
    `define NPC_DECINFO_MULDIV_MUL_MSB   (`NPC_DECINFO_MULDIV_MUL_LSB+1 -1)
`define NPC_DECINFO_MULDIV_MUL  `NPC_DECINFO_MULDIV_MUL_MSB:`NPC_DECINFO_MULDIV_MUL_LSB
    `define NPC_DECINFO_MULDIV_RV64W_LSB    (`NPC_DECINFO_MULDIV_MUL_MSB+1)
    `define NPC_DECINFO_MULDIV_RV64W_MSB    (`NPC_DECINFO_MULDIV_RV64W_LSB+1-1)
`define NPC_DECINFO_MULDIV_RV64W    `NPC_DECINFO_MULDIV_RV64W_MSB:`NPC_DECINFO_MULDIV_RV64W_LSB
    `define NPC_DECINFO_MULDIV_MULH_LSB (`NPC_DECINFO_MULDIV_RV64W_MSB+1)
    `define NPC_DECINFO_MULDIV_MULH_MSB (`NPC_DECINFO_MULDIV_MULH_LSB+1 -1)
`define NPC_DECINFO_MULDIV_MULH `NPC_DECINFO_MULDIV_MULH_MSB:`NPC_DECINFO_MULDIV_MULH_LSB
    `define NPC_DECINFO_MULDIV_MULHSU_LSB   (`NPC_DECINFO_MULDIV_MULH_MSB+1)
    `define NPC_DECINFO_MULDIV_MULHSU_MSB   (`NPC_DECINFO_MULDIV_MULHSU_LSB+1 -1)
`define NPC_DECINFO_MULDIV_MULHSU   `NPC_DECINFO_MULDIV_MULHSU_MSB:`NPC_DECINFO_MULDIV_MULHSU_LSB
    `define NPC_DECINFO_MULDIV_MULHU_LSB    (`NPC_DECINFO_MULDIV_MULHSU_MSB+1)
    `define NPC_DECINFO_MULDIV_MULHU_MSB    (`NPC_DECINFO_MULDIV_MULHU_LSB+1 -1)
`define NPC_DECINFO_MULDIV_MULHU    `NPC_DECINFO_MULDIV_MULHU_MSB:`NPC_DECINFO_MULDIV_MULHU_LSB
    `define NPC_DECINFO_MULDIV_DIV_LSB      (`NPC_DECINFO_MULDIV_MULHU_MSB+1)
    `define NPC_DECINFO_MULDIV_DIV_MSB      (`NPC_DECINFO_MULDIV_DIV_LSB+1 -1)
`define NPC_DECINFO_MULDIV_DIV      `NPC_DECINFO_MULDIV_DIV_MSB:`NPC_DECINFO_MULDIV_DIV_LSB
    `define NPC_DECINFO_MULDIV_DIVU_LSB     (`NPC_DECINFO_MULDIV_DIV_MSB+1)
    `define NPC_DECINFO_MULDIV_DIVU_MSB     (`NPC_DECINFO_MULDIV_DIVU_LSB+1 -1)
`define NPC_DECINFO_MULDIV_DIVU     `NPC_DECINFO_MULDIV_DIVU_MSB:`NPC_DECINFO_MULDIV_DIVU_LSB
    `define NPC_DECINFO_MULDIV_REM_LSB      (`NPC_DECINFO_MULDIV_DIVU_MSB+1)
    `define NPC_DECINFO_MULDIV_REM_MSB      (`NPC_DECINFO_MULDIV_REM_LSB+1 -1)
`define NPC_DECINFO_MULDIV_REM      `NPC_DECINFO_MULDIV_REM_MSB:`NPC_DECINFO_MULDIV_REM_LSB
    `define NPC_DECINFO_MULDIV_REMU_LSB     (`NPC_DECINFO_MULDIV_REM_MSB+1)
    `define NPC_DECINFO_MULDIV_REMU_MSB     (`NPC_DECINFO_MULDIV_REMU_LSB+1 -1)
`define NPC_DECINFO_MULDIV_REMU     `NPC_DECINFO_MULDIV_REMU_MSB:`NPC_DECINFO_MULDIV_REMU_LSB
 
`define NPC_DECINFO_MULDIV_WIDTH    (`NPC_DECINFO_MULDIV_REMU_MSB+1)

//chose loonset group as the final dec info width 
`define NPC_DECINFO_WIDTH   (`NPC_DECINFO_ALU_WIDTH+1)

//memroy access
`define NPC_ADDR_SIZE       `NPC_XLEN
//reg file
`define NPC_RFIDX_WIDTH        5